server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tjdwns000927@gmail.com
    password: rryv rvtm hnnt zolb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/TripTale_project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 
mybatis:
  type-aliases-package: com.example.demo.vo
  mapper-locations: classpath:/mappers/**/*.xml

custom:
    siteName: tripTale
    siteMainUri: http://localhost:8080
    emailFrom: no-reply@localhost
    emailFromName: tripTale
  
